// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAATz8TjYdP4GJJ59Zb8V2TUoalhw0I4',
    appId: '1:14103344418:web:a404f67a01551ab123617b',
    messagingSenderId: '14103344418',
    projectId: 'shoppinglist-81505',
    authDomain: 'shoppinglist-81505.firebaseapp.com',
    storageBucket: 'shoppinglist-81505.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoevC7mKi8Ub8892Ys-bKlvzRLBLAeH2I',
    appId: '1:14103344418:android:0861aed71aedf32323617b',
    messagingSenderId: '14103344418',
    projectId: 'shoppinglist-81505',
    storageBucket: 'shoppinglist-81505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2iW43qgeZnsjgY-zv4y-jTZCH7tHpYFg',
    appId: '1:14103344418:ios:cf3df118bec3ec8023617b',
    messagingSenderId: '14103344418',
    projectId: 'shoppinglist-81505',
    storageBucket: 'shoppinglist-81505.appspot.com',
    androidClientId: '14103344418-c31soue2njbujkfqtr638m63kd562ih8.apps.googleusercontent.com',
    iosClientId: '14103344418-mhbaoue96r1th4lj0teoo98jikre9hv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppinglistProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2iW43qgeZnsjgY-zv4y-jTZCH7tHpYFg',
    appId: '1:14103344418:ios:1ea28107e8d96e8223617b',
    messagingSenderId: '14103344418',
    projectId: 'shoppinglist-81505',
    storageBucket: 'shoppinglist-81505.appspot.com',
    androidClientId: '14103344418-c31soue2njbujkfqtr638m63kd562ih8.apps.googleusercontent.com',
    iosClientId: '14103344418-85tje3jldqc0g16bdih6i1k4mrt8ddmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppinglistProject.RunnerTests',
  );
}
